-- Drop tables in reverse dependency order
DROP TABLE IF EXISTS review_rating_type CASCADE;
DROP TABLE IF EXISTS rating_type CASCADE;
DROP TABLE IF EXISTS review CASCADE;

DROP TABLE IF EXISTS size CASCADE;
DROP TABLE IF EXISTS size_translation CASCADE;
DROP TABLE IF EXISTS size_option CASCADE;
DROP TABLE IF EXISTS size_category CASCADE;
DROP TABLE IF EXISTS size_category_translation CASCADE;

DROP TABLE IF EXISTS product CASCADE;
DROP TABLE IF EXISTS product_translation CASCADE;
DROP TABLE IF EXISTS product_item CASCADE;
DROP TABLE IF EXISTS product_image CASCADE;
DROP TABLE IF EXISTS product_attribute CASCADE;
DROP TABLE IF EXISTS product_category CASCADE;
DROP TABLE IF EXISTS product_category_translation CASCADE;
DROP TABLE IF EXISTS product_variation CASCADE;
DROP TABLE IF EXISTS product_feature CASCADE;
DROP TABLE IF EXISTS product_feature_translation CASCADE;
DROP TABLE IF EXISTS product_features CASCADE;
DROP TABLE IF EXISTS product_part CASCADE;
DROP TABLE IF EXISTS product_part_translation CASCADE;
DROP TABLE IF EXISTS product_composition CASCADE;

DROP TABLE IF EXISTS language CASCADE;

DROP TABLE IF EXISTS care_instruction CASCADE;
DROP TABLE IF EXISTS care_instruction_translation CASCADE;
DROP TABLE IF EXISTS material_care_instructions CASCADE;
DROP TABLE IF EXISTS fabric_type_care_instructions CASCADE;
DROP TABLE IF EXISTS product_care_instructions CASCADE;

DROP TABLE IF EXISTS weight_unit CASCADE;
DROP TABLE IF EXISTS weight_unit_translation CASCADE;

DROP TABLE IF EXISTS attribute_option CASCADE;
DROP TABLE IF EXISTS attribute_type CASCADE;
DROP TABLE IF EXISTS attribute_type_translation CASCADE;
DROP TABLE IF EXISTS attribute_option_translation CASCADE;

DROP TABLE IF EXISTS color CASCADE;
DROP TABLE IF EXISTS color_translation CASCADE;

DROP TABLE IF EXISTS brand CASCADE;
DROP TABLE IF EXISTS brand_translation CASCADE;

DROP TABLE IF EXISTS fabric_type CASCADE;
DROP TABLE IF EXISTS fabric_type_translation CASCADE;
DROP TABLE IF EXISTS fabric_type_features CASCADE;
DROP TABLE IF EXISTS fabric_type_variation CASCADE;
DROP TABLE IF EXISTS fabric_type_composition CASCADE;

DROP TABLE IF EXISTS material CASCADE;
DROP TABLE IF EXISTS material_translation CASCADE;
DROP TABLE IF EXISTS material_feature CASCADE;
DROP TABLE IF EXISTS material_feature_translation CASCADE;
DROP TABLE IF EXISTS material_variation CASCADE;
DROP TABLE IF EXISTS material_features CASCADE;

DROP TABLE IF EXISTS storage_provider CASCADE;
DROP TABLE IF EXISTS bucket CASCADE;
DROP TABLE IF EXISTS directory CASCADE;
DROP TABLE IF EXISTS image CASCADE;

DROP TABLE IF EXISTS cart CASCADE;
DROP TABLE IF EXISTS cart_item CASCADE;

-------------------------------------------------------------------------------------------------

CREATE TABLE language (
  code CHAR(2) PRIMARY KEY CHECK (code ~ '^[a-z]{2}$'),  -- ISO 639-1
  name TEXT NOT NULL UNIQUE,
  direction CHAR(3) NOT NULL CHECK (direction IN ('ltr', 'rtl'))
);

CREATE TABLE care_instruction (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  icon VARCHAR(100) NOT NULL,
  code VARCHAR(50) UNIQUE NOT NULL
);

CREATE TABLE care_instruction_translation (
  care_instruction_id INT NOT NULL REFERENCES care_instruction(id),
  language_code CHAR(2) NOT NULL REFERENCES language(code),
  instruction TEXT NOT NULL,
  PRIMARY KEY (care_instruction_id, language_code),
  UNIQUE (language_code, instruction)
);

CREATE TABLE weight_unit (
  code CHAR(3) PRIMARY KEY
);

CREATE TABLE weight_unit_translation (
  weight_unit_code CHAR(3) REFERENCES weight_unit(code),
  language_code CHAR(2) REFERENCES language(code),
  name TEXT NOT NULL,
  PRIMARY KEY (weight_unit_code, language_code)
);

CREATE TABLE material (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
);

CREATE TABLE material_translation (
  material_id INT NOT NULL REFERENCES material(id),
  language_code CHAR(2) NOT NULL REFERENCES language(code),
  name TEXT NOT NULL,
  PRIMARY KEY (material_id, language_code),
  UNIQUE (language_code, name)
);

CREATE TABLE material_care_instructions (
  material_id INT NOT NULL REFERENCES material(id),
  care_instruction_id INT NOT NULL REFERENCES care_instruction(id),
  PRIMARY KEY (material_id, care_instruction_id)
);

CREATE TABLE material_variation (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  material_id INT NOT NULL REFERENCES material(id),
  weight_unit_code CHAR(3) REFERENCES weight_unit(code),
  weight INT CHECK (weight > 0),
  name TEXT,
  CHECK (
    (weight IS NOT NULL AND weight_unit_code IS NOT NULL AND name IS NULL) OR
    (name IS NOT NULL AND weight IS NULL AND weight_unit_code IS NULL) OR 
    (name IS NOT NULL AND weight IS NOT NULL AND weight_unit_code IS NOT NULL)
  ),
  UNIQUE (material_id, weight, weight_unit_code)
);

CREATE TABLE material_feature (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  icon VARCHAR(100) NOT NULL, 
  code VARCHAR(50) UNIQUE NOT NULL
);

CREATE TABLE material_feature_translation (
  material_feature_id INT NOT NULL REFERENCES material_feature(id),
  language_code CHAR(2) NOT NULL REFERENCES language(code),
  name VARCHAR(100) NOT NULL,
  PRIMARY KEY (material_feature_id, language_code),
  UNIQUE (language_code, name)
);

CREATE TABLE material_features (
  material_id INT NOT NULL REFERENCES material(id),
  material_feature_id INT NOT NULL REFERENCES material_feature(id),
  PRIMARY KEY (material_id, material_feature_id)
);

CREATE TABLE fabric_type (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL UNIQUE
);

CREATE TABLE fabric_type_translation (
  fabric_type_id INT NOT NULL REFERENCES fabric_type(id),
  language_code CHAR(2) NOT NULL REFERENCES language(code),
  about TEXT,
  PRIMARY KEY (fabric_type_id, language_code)
);

CREATE TABLE fabric_type_variation (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  fabric_type_id INT NOT NULL REFERENCES fabric_type(id), 
  weight_unit_code CHAR(3) REFERENCES weight_unit(code),
  weight INT CHECK (weight > 0),
  name TEXT,
  CHECK (
    (weight IS NOT NULL AND weight_unit_code IS NOT NULL AND name IS NULL) OR
    (name IS NOT NULL AND weight IS NULL AND weight_unit_code IS NULL) OR 
    (name IS NOT NULL AND weight IS NOT NULL AND weight_unit_code IS NOT NULL)
  ), 
  UNIQUE (fabric_type_id, weight, weight_unit_code)
);

CREATE TABLE fabric_type_composition (
  fabric_type_variation_id INT NOT NULL REFERENCES fabric_type_variation(id),
  material_id INT NOT NULL REFERENCES material(id),
  percentage INT NOT NULL CHECK (percentage BETWEEN 1 AND 100),
  PRIMARY KEY (fabric_type_variation_id, material_id)
);

CREATE TABLE fabric_type_features (
  fabric_type_id INT NOT NULL REFERENCES fabric_type(id),
  material_feature_id INT NOT NULL REFERENCES material_feature(id),
  PRIMARY KEY (fabric_type_id, material_feature_id)
);

CREATE TABLE fabric_type_care_instructions (
  fabric_type_id INT NOT NULL REFERENCES fabric_type(id),
  care_instruction_id INT NOT NULL REFERENCES care_instruction(id),
  PRIMARY KEY (fabric_type_id, care_instruction_id)
);

CREATE TABLE size (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
);

CREATE TABLE size_category (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
);

CREATE TABLE size_option (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sort_order INT NOT NULL,
  size_category_id INT NOT NULL REFERENCES size_category(id),
  size_id INT NOT NULL REFERENCES size(id), 
  UNIQUE (size_id, size_category_id)
);

CREATE TABLE size_translation (
  size_id INT NOT NULL REFERENCES size(id),
  language_code CHAR(2) NOT NULL REFERENCES language(code),
  name TEXT NOT NULL,
  PRIMARY KEY (size_id, language_code),
  UNIQUE (language_code, name)
);

CREATE TABLE attribute_type (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
);

CREATE TABLE attribute_option (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  attribute_type_id INT NOT NULL REFERENCES attribute_type(id)
);

CREATE TABLE brand (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL UNIQUE
);

CREATE TABLE color (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  hex TEXT NOT NULL UNIQUE
);

CREATE TABLE storage_provider (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL CHECK (name ~ '^[a-z0-9-]{3,50}$'),
  base_url TEXT NOT NULL UNIQUE CHECK (base_url ~ '^https?://[a-z0-9.-]+$'),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (name, base_url)
);

CREATE TABLE bucket (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  region TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  storage_provider_id INT NOT NULL REFERENCES storage_provider(id), 
  UNIQUE (name, storage_provider_id)
);

CREATE TABLE directory (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  bucket_id INT NOT NULL REFERENCES bucket(id) ON DELETE CASCADE,
  path TEXT NOT NULL CHECK (path ~ '^[a-z0-9/-]+$' AND path !~ '^/' AND path !~ '/$'),
  UNIQUE (bucket_id, path)
);

CREATE TABLE image (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  directory_id INT NOT NULL REFERENCES directory(id),
  filename TEXT NOT NULL,
  alt_text TEXT NOT NULL CHECK (length(alt_text) BETWEEN 0 AND 200),
  mime_type TEXT NOT NULL CHECK (mime_type IN ('image/jpg', 'image/jpeg',  'image/png',  'image/webp',  'image/avif')),
  width INT CHECK (width BETWEEN 100 AND 16384),
  height INT CHECK (height BETWEEN 100 AND 16384),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (directory_id, filename)
);

CREATE TABLE product_category (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  image TEXT,
  parent_product_category_id INT REFERENCES product_category(id),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE product (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  slug TEXT UNIQUE,
  is_published BOOLEAN,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  product_category_id INT REFERENCES product_category(id),
  brand_id INT REFERENCES brand(id)
);

CREATE TABLE product_translation (
  name TEXT NOT NULL,
  description TEXT NOT NULL,
  care_instructions TEXT,
  about TEXT,
  product_id INT NOT NULL REFERENCES product(id),
  language_code CHAR(2) NOT NULL REFERENCES language(code),
  PRIMARY KEY (product_id, language_code),
  UNIQUE (language_code, name)
);

CREATE TABLE product_care_instructions (
  product_id INT NOT NULL REFERENCES product(id),
  care_instruction_id INT NOT NULL REFERENCES care_instruction(id),
  PRIMARY KEY (product_id, care_instruction_id)
);

CREATE TABLE product_part (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
);

CREATE TABLE product_part_translation (
  product_part_id INT NOT NULL REFERENCES product_part(id),
  language_code CHAR(2) NOT NULL REFERENCES language(code),
  name TEXT NOT NULL,
  PRIMARY KEY (product_part_id, language_code),
  UNIQUE (language_code, name)
);

CREATE TABLE product_composition (
  product_id INT NOT NULL REFERENCES product(id),
  product_part_id INT NOT NULL REFERENCES product_part(id),
  material_variation_id INT REFERENCES material_variation(id),
  fabric_type_variation_id INT REFERENCES fabric_type_variation(id),
  percentage INT NOT NULL CHECK (percentage BETWEEN 1 AND 100),
  
  -- Generated column to create a non-null composite key
  component_id INT GENERATED ALWAYS AS (
    COALESCE(material_variation_id, fabric_type_variation_id)
  ) STORED,
  
  CHECK (
    (material_variation_id IS NULL) <> (fabric_type_variation_id IS NULL)
  ),
  
  PRIMARY KEY (product_id, product_part_id, component_id)
);

CREATE TABLE product_feature (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
);

CREATE TABLE product_feature_translation (
  product_feature_id INT NOT NULL REFERENCES product_feature(id),
  language_code CHAR(2) NOT NULL REFERENCES language(code),
  name TEXT NOT NULL,
  PRIMARY KEY (product_feature_id, language_code),
  UNIQUE (language_code, name)
);

CREATE TABLE product_features (
  product_id INT NOT NULL REFERENCES product(id),
  product_feature_id INT NOT NULL REFERENCES product_feature(id),
  PRIMARY KEY (product_id, product_feature_id)
);

CREATE TABLE product_attribute (
  product_id INT REFERENCES product(id),
  attribute_option_id INT REFERENCES attribute_option(id),
  PRIMARY KEY (product_id, attribute_option_id)
);

CREATE TABLE product_item (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  price INT NOT NULL,
  sale_price INT,
  sku TEXT NOT NULL UNIQUE, 
  -- model_wearing TEXT,
  -- model_height TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  product_id INT NOT NULL REFERENCES product(id),
  color_id INT NOT NULL REFERENCES color(id)
);

CREATE TABLE product_image (
  image_id INT NOT NULL REFERENCES image(id),
  product_item_id INT REFERENCES product_item(id) ON DELETE CASCADE,
  sort_order INT NOT NULL CHECK (sort_order BETWEEN 1 AND 100),
  PRIMARY KEY (image_id, product_item_id)
);

CREATE TABLE product_variation (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  stock INT NOT NULL CHECK (stock >= 0),
  weight INT NOT NULL CHECK (weight > 0),
  weight_unit_code CHAR(3) NOT NULL REFERENCES weight_unit(code),
  product_item_id INT NOT NULL REFERENCES product_item(id),
  size_option_id INT NOT NULL REFERENCES size_option(id),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (product_item_id, size_option_id)
);

CREATE TABLE review (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  rating INT NOT NULL CHECK (rating BETWEEN 1 AND 5),
  comment TEXT NOT NULL,
  date DATE NOT NULL DEFAULT CURRENT_DATE,
  product_id INT NOT NULL REFERENCES product(id),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE rating_type (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL UNIQUE,
  label_min TEXT,
  label_max TEXT
);

CREATE TABLE review_rating_type (
  value INT NOT NULL,
  review_id INT REFERENCES review(id),
  rating_type_id INT REFERENCES rating_type(id),
  PRIMARY KEY (review_id, rating_type_id)
);
CREATE TABLE color_translation (
  color_id INT NOT NULL REFERENCES color(id),
  language_code CHAR(2) NOT NULL REFERENCES language(code),
  name TEXT NOT NULL,
  PRIMARY KEY (color_id, language_code),
  UNIQUE (language_code, name)
);

CREATE TABLE brand_translation (
  brand_id INT NOT NULL REFERENCES brand(id),
  language_code CHAR(2) NOT NULL REFERENCES language(code),
  description TEXT NOT NULL,
  PRIMARY KEY (brand_id, language_code)
);

CREATE TABLE product_category_translation (
  product_category_id INT NOT NULL REFERENCES product_category(id), 
  language_code CHAR(2) NOT NULL REFERENCES language(code),
  name TEXT NOT NULL,
  description TEXT NOT NULL,
  PRIMARY KEY (product_category_id, language_code), 
  UNIQUE (language_code, name)  
);

CREATE TABLE size_category_translation (
  size_category_id INT NOT NULL REFERENCES size_category(id),
  language_code CHAR(2) NOT NULL REFERENCES language(code),
  name TEXT NOT NULL, 
  PRIMARY KEY (size_category_id, language_code),
  UNIQUE (language_code, name)
);

CREATE TABLE attribute_type_translation (
  attribute_type_id INT NOT NULL REFERENCES attribute_type(id), 
  language_code CHAR(2) NOT NULL REFERENCES language(code),
  name TEXT NOT NULL,
  PRIMARY KEY (attribute_type_id, language_code),
  UNIQUE (language_code, name)
);

CREATE TABLE attribute_option_translation (
  attribute_option_id INT NOT NULL REFERENCES attribute_option(id),
  language_code CHAR(2) NOT NULL REFERENCES language(code),
  name TEXT NOT NULL,
  PRIMARY KEY (attribute_option_id, language_code), 
  UNIQUE (language_code, name)
);

CREATE TABLE cart (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  expires_at TIMESTAMPTZ GENERATED ALWAYS AS (
    created_at  + interval '1 hour'
  ) STORED
);

CREATE TABLE cart_item (
  cart_id UUID NOT NULL REFERENCES cart(id) ON DELETE CASCADE,
  product_variation_id INT NOT NULL REFERENCES product_variation(id),
  quantity INT NOT NULL CHECK (quantity > 0),
  price INT NOT NULL CHECK (price > 0),
  added_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  PRIMARY KEY (cart_id, product_variation_id)
);

CREATE OR REPLACE FUNCTION update_cart_expiration()
RETURNS TRIGGER AS $$
BEGIN
  NEW.expires_at = NEW.updated_at + INTERVAL '30 days';
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER cart_expiration_trigger
BEFORE INSERT OR UPDATE ON cart
FOR EACH ROW
EXECUTE FUNCTION update_cart_expiration();

ALTER TABLE review_rating_type ENABLE ROW LEVEL SECURITY;
ALTER TABLE rating_type ENABLE ROW LEVEL SECURITY;
ALTER TABLE review ENABLE ROW LEVEL SECURITY;

ALTER TABLE product_variation ENABLE ROW LEVEL SECURITY;
ALTER TABLE product_item ENABLE ROW LEVEL SECURITY;
ALTER TABLE product_image ENABLE ROW LEVEL SECURITY;
ALTER TABLE product_attribute ENABLE ROW LEVEL SECURITY;
ALTER TABLE product ENABLE ROW LEVEL SECURITY;
ALTER TABLE product_category ENABLE ROW LEVEL SECURITY;
ALTER TABLE product_translation ENABLE ROW LEVEL SECURITY;
ALTER TABLE product_category_translation ENABLE ROW LEVEL SECURITY;
ALTER TABLE product_feature ENABLE ROW LEVEL SECURITY;
ALTER TABLE product_part ENABLE ROW LEVEL SECURITY;
ALTER TABLE product_part_translation ENABLE ROW LEVEL SECURITY;
ALTER TABLE product_features ENABLE ROW LEVEL SECURITY;
ALTER TABLE product_feature ENABLE ROW LEVEL SECURITY;
ALTER TABLE product_feature_translation ENABLE ROW LEVEL SECURITY;
ALTER TABLE product_composition ENABLE ROW LEVEL SECURITY;

ALTER TABLE color ENABLE ROW LEVEL SECURITY;
ALTER TABLE color_translation ENABLE ROW LEVEL SECURITY;

ALTER TABLE brand ENABLE ROW LEVEL SECURITY;
ALTER TABLE brand_translation ENABLE ROW LEVEL SECURITY;

ALTER TABLE size_option ENABLE ROW LEVEL SECURITY;
ALTER TABLE size_category ENABLE ROW LEVEL SECURITY;
ALTER TABLE size_category_translation ENABLE ROW LEVEL SECURITY;
ALTER TABLE size ENABLE ROW LEVEL SECURITY;
ALTER TABLE size_translation ENABLE ROW LEVEL SECURITY;

ALTER TABLE attribute_option ENABLE ROW LEVEL SECURITY;
ALTER TABLE attribute_type ENABLE ROW LEVEL SECURITY;
ALTER TABLE attribute_type_translation ENABLE ROW LEVEL SECURITY;
ALTER TABLE attribute_option_translation ENABLE ROW LEVEL SECURITY;

ALTER TABLE language ENABLE ROW LEVEL SECURITY;

ALTER TABLE care_instruction ENABLE ROW LEVEL SECURITY;
ALTER TABLE care_instruction_translation ENABLE ROW LEVEL SECURITY;
ALTER TABLE material_care_instructions ENABLE ROW LEVEL SECURITY;
ALTER TABLE fabric_type_care_instructions ENABLE ROW LEVEL SECURITY;
ALTER TABLE product_care_instructions ENABLE ROW LEVEL SECURITY;

ALTER TABLE weight_unit ENABLE ROW LEVEL SECURITY;
ALTER TABLE weight_unit_translation ENABLE ROW LEVEL SECURITY;

ALTER TABLE material ENABLE ROW LEVEL SECURITY;
ALTER TABLE material_translation ENABLE ROW LEVEL SECURITY;
ALTER TABLE material_variation ENABLE ROW LEVEL SECURITY;
ALTER TABLE material_feature ENABLE ROW LEVEL SECURITY;
ALTER TABLE material_feature_translation ENABLE ROW LEVEL SECURITY;
ALTER TABLE material_features ENABLE ROW LEVEL SECURITY;

ALTER TABLE fabric_type ENABLE ROW LEVEL SECURITY;
ALTER TABLE fabric_type_translation ENABLE ROW LEVEL SECURITY;
ALTER TABLE fabric_type_features ENABLE ROW LEVEL SECURITY;
ALTER TABLE fabric_type_variation ENABLE ROW LEVEL SECURITY;
ALTER TABLE fabric_type_composition ENABLE ROW LEVEL SECURITY;

ALTER TABLE storage_provider ENABLE ROW LEVEL SECURITY;
ALTER TABLE bucket ENABLE ROW LEVEL SECURITY;
ALTER TABLE directory ENABLE ROW LEVEL SECURITY;
ALTER TABLE image ENABLE ROW LEVEL SECURITY;

ALTER TABLE cart ENABLE ROW LEVEL SECURITY;
ALTER TABLE cart_item ENABLE ROW LEVEL SECURITY;

-- CREATE VIEW image_url AS
-- SELECT 
--   i.id,
--   sp.base_url || '/' || 
--   b.name || '/' || 
--   d.path || '/' || 
--   i.filename || '.' || 
--   CASE 
--     WHEN i.mime_type = 'image/jpeg' THEN 'jpg'
--     WHEN i.mime_type = 'image/png' THEN 'png'
--     WHEN i.mime_type = 'image/webp' THEN 'webp'
--     WHEN i.mime_type = 'image/avif' THEN 'avif'
--     ELSE 'bin' 
--   END AS url
-- FROM image i
-- JOIN directory d ON i.directory_id = d.id
-- JOIN bucket b ON d.bucket_id = b.id
-- JOIN storage_provider sp ON b.storage_provider_id = sp.id;

CREATE OR REPLACE PROCEDURE enable_table_read_access(table_name TEXT)
LANGUAGE plpgsql
AS $$
BEGIN
    EXECUTE format('
        CREATE POLICY "Enable read access for all users"
        ON %I for select
        to anon      
        using ( true ); 
    ', table_name, table_name);
END;
$$;

CALL enable_table_read_access('review_rating_type');
CALL enable_table_read_access('rating_type');
CALL enable_table_read_access('review');

CALL enable_table_read_access('product');
CALL enable_table_read_access('product_translation');
CALL enable_table_read_access('product_category');
CALL enable_table_read_access('product_category_translation');
CALL enable_table_read_access('product_item');
CALL enable_table_read_access('product_image');
CALL enable_table_read_access('product_attribute');
CALL enable_table_read_access('product_variation');
CALL enable_table_read_access('product_part');
CALL enable_table_read_access('product_part_translation');
CALL enable_table_read_access('product_feature');
CALL enable_table_read_access('product_feature_translation');
CALL enable_table_read_access('product_composition');
CALL enable_table_read_access('product_features');

CALL enable_table_read_access('size_option');
CALL enable_table_read_access('size_category');
CALL enable_table_read_access('size');
CALL enable_table_read_access('size_category_translation');
CALL enable_table_read_access('size_translation');

CALL enable_table_read_access('color');
CALL enable_table_read_access('color_translation');

CALL enable_table_read_access('brand');
CALL enable_table_read_access('brand_translation');

CALL enable_table_read_access('language');

CALL enable_table_read_access('care_instruction');
CALL enable_table_read_access('care_instruction_translation');
CALL enable_table_read_access('material_care_instructions');
CALL enable_table_read_access('fabric_type_care_instructions');
CALL enable_table_read_access('product_care_instructions');

CALL enable_table_read_access('weight_unit');
CALL enable_table_read_access('weight_unit_translation');

CALL enable_table_read_access('attribute_option');
CALL enable_table_read_access('attribute_type');
CALL enable_table_read_access('attribute_type_translation');
CALL enable_table_read_access('attribute_option_translation');

CALL enable_table_read_access('material');
CALL enable_table_read_access('material_translation');
CALL enable_table_read_access('material_variation');
CALL enable_table_read_access('material_feature');
CALL enable_table_read_access('material_feature_translation');
CALL enable_table_read_access('material_features');

CALL enable_table_read_access('fabric_type');
CALL enable_table_read_access('fabric_type_translation');
CALL enable_table_read_access('fabric_type_features');
CALL enable_table_read_access('fabric_type_variation');
CALL enable_table_read_access('fabric_type_composition');

CALL enable_table_read_access('storage_provider');
CALL enable_table_read_access('bucket');
CALL enable_table_read_access('directory');
CALL enable_table_read_access('image');

CALL enable_table_read_access('cart');
CALL enable_table_read_access('cart_item');

-- handle time stamp updates
CREATE OR REPLACE FUNCTION update_modified_column() 
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER update_product_modtime 
BEFORE UPDATE ON product 
FOR EACH ROW EXECUTE FUNCTION update_modified_column();

CREATE TRIGGER update_product_item_modtime 
BEFORE UPDATE ON product_item 
FOR EACH ROW EXECUTE FUNCTION update_modified_column();

-- Indexing
CREATE INDEX idx_product_slug ON product(slug);
CREATE INDEX idx_product_category_parent ON product_category(parent_product_category_id);
CREATE INDEX idx_product_item_sku ON product_item(sku);
CREATE INDEX idx_product_item_id ON product_item(id);
CREATE INDEX idx_color_translation_lang ON color_translation(language_code);
CREATE INDEX idx_variation_stock ON product_variation(stock) WHERE stock > 0;
CREATE INDEX idx_variation_item_size ON product_variation(product_item_id, size_option_id);
CREATE INDEX idx_review_product ON review(product_id);
CREATE INDEX idx_review_rating_value ON review_rating_type(value);
CREATE INDEX idx_attribute_option_type ON attribute_option(attribute_type_id);
-- CREATE INDEX idx_order_user ON user_order(user_id);
-- CREATE INDEX idx_order_status ON user_order(status_id);
-- CREATE INDEX idx_order_items_product ON order_item(product_item_id);
-- CREATE INDEX idx_address_country ON user_address(country_code);
-- CREATE INDEX idx_currency_active ON currency(is_active) WHERE is_active;
-- CREATE INDEX idx_country_continent ON country(continent_code);
-- CREATE INDEX idx_locale_active ON locale(is_active) WHERE is_active;

INSERT INTO language (code, name, direction) VALUES
  ('en', 'English', 'ltr'),
  ('de', 'Deutsch', 'ltr');

INSERT INTO care_instruction (id, icon, code) VALUES 
  (1, 'mdi:washing-machine', 'machine_wash_warm'), 
  (2, 'mdi:washing-machine', 'machine_wash_cold'),
  (3, 'mdi:washing-machine', 'machine_wash_hot'),
  (4, 'mdi:flask-empty-off', 'do_not_use_bleach'),
  (5, 'mdi:tumble-dryer', 'do_not_iron'),
  (6, 'mdi:flask-empty-off', 'do_not_use_fabric_softeners'),
  (7, 'mdi:tumble-dryer', 'do_not_tumble_dry'),
  (8, 'mdi:close-circle', 'do_not_dry_clean'), 
  (9, 'mdi:square-circle-outline', 'tumble_dry_low '),
  (10, 'mdi:unicycle', 'wool_cycle'),
  (11, 'mdi:unicycle', 'normal_cycle'),
  (12, 'mdi:tumble-dryer', 'lay_flat_to_dry'),
  (13, 'mdi:tumble-dryer', 'dry_on_low_heat'),
  (14, 'mdi:tumble-dryer', 'air_dry_flat'),
  (15, 'mdi:spray-bottle', 'use_mild_detergent'),
  (16, 'mdi:hanger', 'hang_to_dry');

INSERT INTO care_instruction_translation (care_instruction_id, language_code, instruction) VALUES 
  (1, 'en', 'Machine wash warn'),
  (2, 'en', 'Machine wash cold'),
  (3, 'en', 'Machine wash hot'),
  (4, 'en', 'Do not use bleach'),
  (5, 'en', 'Do not iron'),
  (6, 'en', 'Do not use fabric softeners'),
  (7, 'en', 'Do not tumble dry'),
  (8, 'en', 'Do not dry clean'), 
  (9, 'en', 'Tumble dry low'),
  (10, 'en', 'Wool cycle'),
  (11, 'en', 'Normal cycle'),
  (12, 'en', 'Lay flat to dry'),
  (13, 'en', 'Dry on low heat'),
  (14, 'en', 'Air dry flat'),
  (15, 'en', 'Use mild detergent'),
  (16, 'en', 'Hang to dry');

INSERT INTO weight_unit (code) VALUES ('g'), ('kg'), ('gsm');

INSERT INTO weight_unit_translation (weight_unit_code, language_code, name) VALUES
  ('g', 'en', 'Gram'),
  ('g', 'de', 'Gramm'),
  ('kg', 'en', 'Kilogram'),
  ('kg', 'de', 'Kilogramm'),
  ('gsm', 'en', 'Grams per square meter'),
  ('gsm', 'de', 'Gramm pro Quadratmeter');

INSERT INTO color (hex) VALUES 
  ('FF0000'), 
  ('000000');

INSERT INTO color_translation (color_id, language_code, name) VALUES
  (1, 'en', 'Red'),
  (1, 'de', 'Rot'),
  (2, 'en', 'Black'),
  (2, 'de', 'Schwarz');

INSERT INTO brand (name) VALUES
  ('Revar');  

INSERT INTO brand_translation (brand_id, language_code, description) VALUES
  (1, 'en', 'Revar Brand Description'),
  (1, 'de', 'Revar Markenbeschreibung');

INSERT INTO size (id) VALUES 
  (1),(2),(3),(4),(5),(6),(7),(8),(9),(10),(11),(12);

INSERT INTO size_translation(size_id, language_code, name) VALUES
  (1, 'en', 'XXS'),
  (2, 'en', 'XS'),
  (3, 'en', 'S'),
  (4, 'en', 'M'),
  (5, 'en', 'L'),
  (6, 'en', 'XL'),
  (7, 'en', '2XL'),
  (8, 'en', '3XL'),
  (9, 'en', '36-39'),
  (10, 'en', '40-43'),
  (11, 'en', '44-47'),
  (12, 'en', 'One size'),
  (1, 'de', 'XXS'),
  (2, 'de', 'XS'),
  (3, 'de', 'S'),
  (4, 'de', 'M'),
  (5, 'de', 'L'),
  (6, 'de', 'XL'),
  (7, 'de', '2XL'),
  (8, 'de', '3XL'),
  (9, 'de', '36-39'),
  (10, 'de', '40-43'),
  (11, 'de', '44-47'),
  (12, 'de', 'Ohne Groese');

INSERT INTO size_category DEFAULT VALUES;  -- Tops (id=1)
INSERT INTO size_category DEFAULT VALUES;  -- Bottoms (id=2)
INSERT INTO size_category DEFAULT VALUES;  -- Socks (id=3)
INSERT INTO size_category_translation (size_category_id, language_code, name) VALUES
  (1, 'en', 'Tops'), (1, 'de', 'Oberteile'),
  (2, 'en', 'Bottoms'), (2, 'de', 'Hosen'),
  (3, 'en', 'Socks'), (3, 'de', 'Socken');

INSERT INTO size_option (size_id, size_category_id, sort_order) VALUES
  -- Tops Sizes
  (1, 1, 1),  -- XXS
  (2, 1, 2),  -- XS
  (3, 1, 3),  -- S
  (4, 1, 4),  -- M
  (5, 1, 5),  -- L
  (6, 1, 6),  -- XL
  (7, 1, 7),  -- 2XL
  (8, 1, 8),  -- 3XL
  
  -- Bottoms Sizes
  (1, 2, 1),  -- XXS
  (2, 2, 2),  -- XS
  (3, 2, 3),  -- S
  (4, 2, 4),  -- M
  (5, 2, 5),  -- L
  (6, 2, 6),  -- XL
  (7, 2, 7),  -- 2XL
  (8, 2, 8),  -- 3XL

  -- Socks Sizes
  (9, 3, 1),  -- 36-39
  (10, 3, 2),  -- 40-43
  (11, 3, 3);  -- 44-47

INSERT INTO material (id) VALUES 
  (1), -- Polyester
  (2); -- Merino Wool

INSERT INTO material_translation (material_id, language_code, name) VALUES
  (1, 'en', 'Polyester'),
  (1, 'de', 'Polyester'),
  (2, 'en', 'Merino Wool'),
  (2, 'de', 'Merino Wolle');

INSERT INTO material_care_instructions (material_id, care_instruction_id) VALUES 
  (1, 1), 
  (1, 4), 
  (1, 6), 
  (1, 13),
  (2, 4), 
  (2, 6), 
  (2, 2), 
  (2, 14); 

INSERT INTO material_variation (material_id, weight, weight_unit_code) VALUES 
  (1, 100, 'gsm'),
  (1, 150, 'gsm'),
  (1, 200, 'gsm'),
  (2, 100, 'gsm'),
  (2, 150, 'gsm'),
  (2, 200, 'gsm');

INSERT INTO material_feature (id, code, icon) VALUES 
  (1, 'regulates_warmth', 'mdi:sun-snowflake-variant'),
  (2, 'odor_resistant', 'mdi:odorless'),
  (3, 'fast_drying', 'mdi:water-evaporation'),
  (4, 'breathable', 'mdi:air-filter'),
  (5, 'durable', 'mdi:shield'),
  (6, 'moisture_wicking', 'mdi:format-text-wrapping-overflow'),
  (7, 'lightweight', 'mdi:feather'),
  (8, 'soft', 'mdi:sofa'),
  (9, 'highly_breathable', 'mdi:air-filter'),
  (10, 'compressible', 'mdi:compress'),
  (11, 'dual_surface', 'mdi:layers'),
  (12, 'resists_abrasion', 'mdi:shield'),
  (13, 'four_way_stretch', 'mdi:arrow-expand-all'),
  (14, 'two_way_stretch', 'mdi:arrow-left-right'),
  (15, 'shape_retention', 'mdi:shape-outline'),
  (16, 'superior_wicking', 'mdi:format-text-wrapping-overflow'),
  (17, 'encapsulated_air', 'mdi:weather-windy');

INSERT INTO material_feature_translation (material_feature_id, language_code, name) VALUES
  (1, 'en', 'Regulates warmth'),
  (2, 'en', 'Odor resistant'),
  (3, 'en', 'Fast drying'),
  (4, 'en', 'Breathable'),
  (5, 'en', 'Durable'),
  (6, 'en', 'Moisture wicking'),
  (7, 'en', 'Lightweight'),
  (8, 'en', 'Soft'),
  (9, 'en', 'Highly breathable'),
  (10, 'en', 'Compressible'),
  (11, 'en', 'Dual surface'),
  (12, 'en', 'Resists abrasion'),
  (13, 'en', 'Four-way stretch'),
  (14, 'en', 'Two-way stretch'),
  (15, 'en', 'Shape retention'),
  (16, 'en', 'Superior wicking'),
  (17, 'en', 'Encapsulated air');

INSERT INTO  material_features (material_id, material_feature_id) VALUES
  -- Merino
  (2, 1), (2, 2), (2, 6),
  -- Polyester
  (1, 5), (1, 16), (1, 3);

INSERT INTO fabric_type (id, name) VALUES
  (1, 'Polartec Alpha Direct'),
  (2, 'Polartec Power Wool');

INSERT INTO fabric_type_translation (fabric_type_id, language_code) VALUES
  -- Alpha Direct
  (1, 'en'),
  (1, 'de'),
  -- Power Wool
  (2, 'en'),
  (2, 'de');

INSERT INTO fabric_type_care_instructions (fabric_type_id, care_instruction_id) VALUES 
  (1, 1), 
  (1, 11), 
  (1, 15), 
  (1, 4),
  (1, 6),
  (1, 9),
  (1, 8),
  (2, 2), 
  (2, 15), 
  (2, 16);
  
INSERT INTO fabric_type_variation (weight, fabric_type_id, name, weight_unit_code) VALUES
  (60, 1, NULL, 'gsm'),
  (90, 1, NULL, 'gsm'),
  (120, 1, NULL, 'gsm'),
  (100, 2, 'Silkweight', 'gsm'),
  (145, 2, 'Lightweight', 'gsm'),
  (150, 2, 'Lightweight', 'gsm'),
  (200, 2, 'Midweight', 'gsm');

INSERT INTO fabric_type_composition (fabric_type_variation_id, material_id, percentage) VALUES
  (1, 1, 100),
  (2, 1, 100),
  (3, 1, 100),
  (4, 1, 65),
  (4, 2, 35),
  (5, 1, 65),
  (5, 2, 35),
  (6, 1, 65),
  (6, 2, 35);
  
INSERT INTO fabric_type_features (fabric_type_id, material_feature_id) VALUES
  -- Alpha Direct
  (1,1), (1,7), (1, 9), (1, 3), (1, 10),
  -- Power Wool
  (2, 11), (2, 12), (2, 13), (2, 15), (2, 9), (2, 16);

INSERT INTO attribute_type DEFAULT VALUES;  -- Fit (id=1)
INSERT INTO attribute_type_translation (attribute_type_id, language_code, name) VALUES
  (1, 'en', 'Fit'),
  (1, 'de', 'Passform');

INSERT INTO attribute_option (attribute_type_id) VALUES (1), (1), (1);  -- Creates 3 options
INSERT INTO attribute_option_translation (attribute_option_id, language_code, name) VALUES
  (1, 'en', 'Regular'), (1, 'de', 'Regulär'),
  (2, 'en', 'Slim'), (2, 'de', 'Schmal'),
  (3, 'en', 'Relaxed'), (3, 'de', 'Locker');

INSERT INTO product_category (parent_product_category_id) VALUES
  (NULL), -- Top
  (NULL), --Bottom 
  (NULL), --Accessories
  (1), --Hoodies
  (2), --Pants
  (3); --Socks

INSERT INTO product_category_translation (product_category_id, language_code, name, description) VALUES
  (1, 'en', 'Tops', ''),
  (2, 'en', 'Bottoms', ''),
  (3, 'en', 'Accessories', ''),
  (4, 'en', 'Hoodies', ''),
  (5, 'en', 'Pants', ''),
  (6, 'en', 'Socks', ''),
  (1, 'de', 'Oberteile', ''),
  (2, 'de', 'Unterteile', ''),  
  (3, 'de', 'Accessories', ''),
  (4, 'de', 'Kapuzenpullover', ''),
  (5, 'de', 'Hosen', ''),  
  (6, 'de', 'Socken', '');

INSERT INTO product (slug, product_category_id, brand_id, is_published) VALUES 
  ('alpha-hoodie-60', 4, 1, true),
  ('alpha-pants-60', 5, 1, true),
  ('alpha-socks-60', 6, 1, true),
  ('power-wool-hoodie-lightweight', 4, 1, true),
  ('alpha-hat-60', 3, 1, true);

INSERT INTO product_translation (product_id, language_code, name, description) VALUES
  (1, 'en', 'Revar Alpha Hoodie 60', 'Explorer alpha the perfect GPACKS second layer to always take with you on your adventures, warm, light and breathable.'),
  (1, 'de', 'Revar Alpha Kapuzenpullover 60', 'Produktbeschreibung'),
  (2, 'en', 'Revar Alpha Pants 60', 'Explorer alpha the perfect GPACKS second layer to always take with you on your adventures, warm, light and breathable.'),
  (2, 'de', 'Revar Alpha Hose 60', 'Produktbeschreibung'),
  (3, 'en', 'Revar Alpha Socks 60', 'Explorer alpha the perfect GPACKS second layer to always take with you on your adventures, warm, light and breathable.'),
  (3, 'de', 'Revar Alpha Socken 60', 'Produktbeschreibung'),
  (4, 'en', 'Revar Power Wool Hoodie Lightweight', 'something about the product'),
  (4, 'de', 'Revar Power Wool Kapuzenpullover', 'Produktbeschreibung'),
  (5, 'en', 'Revar Alpha Hat', 'something about the product'),
  (5, 'de', 'Revar Alpha Muetze', 'Produktbeschreibung');

INSERT INTO product_item (price, sale_price, sku, product_id, color_id) VALUES 
  (110, 100, 'ALPHA-HOODIE-RED-60', 1, 1),
  (110, NULL, 'ALPHA-HOODIE-BLACK-60', 1, 2),
  (90, NULL, 'ALPHA-PANTS-RED-60', 2, 1),
  (90, NULL, 'ALPHA-PANTS-BLACK-60', 2, 2),
  (30, NULL, 'ALPHA-SOCKS-RED-60', 3, 1),
  (30, NULL, 'ALPHA-SOCKS-BLACK-60', 3, 2),
  (80, NULL, 'POWER-WOOL-HOODIE-LIGHTWEIGHT-BLACK', 4, 2),
  (26, NULL, 'ALPHA-HAT-RED-60', 5, 1),
  (26, NULL, 'ALPHA-HAT-BLACK-60', 5, 2);

INSERT INTO product_variation (product_item_id, size_option_id, stock, weight, weight_unit_code) VALUES
  (1, 1, 3, 155, 'g'), (1, 2, 1, 194, 'g'), (1, 3, 0, 227, 'g'), (1, 4, 3, 155, 'g'), (1, 5, 1, 194, 'g'), (1, 6, 2, 227, 'g'), (1, 7, 2, 227, 'g'),
  (2, 1, 0, 155, 'g'), (2, 2, 1, 194, 'g'), (2, 3, 2, 227, 'g'), (2, 4, 3, 155, 'g'), (2, 5, 1, 194, 'g'), (2, 6, 0, 227, 'g'), (2, 7, 2, 227, 'g'),
  (3, 11, 5, 155, 'g'), (3, 12, 1, 194, 'g'), (3, 13, 2, 227, 'g'),
  (4, 11, 0, 155, 'g'), (4, 12, 3, 194, 'g'), (4, 13, 5, 227, 'g'),
  (5, 17, 1, 155, 'g'), (5, 18, 3, 194, 'g'), (5, 19, 2, 227, 'g'),
  (6, 17, 1, 155, 'g'), (6, 18, 1, 194, 'g'), (6, 19, 6, 227, 'g'),
  (7, 3, 1, 155, 'g'), (7, 4, 1, 194, 'g'), (7, 5, 6, 227, 'g'),
  (8, 3, 1, 155, 'g'), (8, 4, 1, 194, 'g'), (8, 5, 1, 227, 'g'),
  (9, 3, 1, 155, 'g'), (9, 4, 1, 194, 'g'), (9, 5, 1, 227, 'g');

INSERT INTO product_attribute (product_id, attribute_option_id) VALUES
  (1, 1),   
  (2, 1),  
  (4, 1); 

INSERT INTO product_part (id) VALUES 
  (1), -- fully
  (2), -- body
  (3), -- sleeves
  (4), -- cuffs
  (5), -- hoodie
  (6), -- shoulders
  (7), -- sides
  (8), -- waist
  (9), -- back
  (10), -- front
  (11), -- inside
  (12), -- outside
  (13), -- rest
  (14), -- top
  (15); -- bottom

INSERT INTO product_part_translation (product_part_id, language_code, name) VALUES 
  (1, 'en', 'Fully'),  
  (2, 'en', 'Body'),  
  (3, 'en', 'Sleeves'),  
  (4, 'en', 'Cuffs'),  
  (5, 'en', 'Hoodie'),  
  (6, 'en', 'Shoulders'),  
  (7, 'en', 'Sides'),  
  (8, 'en', 'Waist'),  
  (9, 'en', 'Back'),
  (10, 'en', 'Front'),
  (11, 'en', 'Inside'),
  (12, 'en', 'Outside'),
  (13, 'en', 'The rest'),
  (14, 'en', 'Top'),
  (15, 'en', 'Bottom');

INSERT INTO product_composition (product_id, product_part_id, material_variation_id, fabric_type_variation_id, percentage) VALUES 
  (1, 1, NULL, 1, 100),
  (2, 1, NULL, 1, 100),
  (3, 1, NULL, 1, 100),
  (4, 1, NULL, 5, 100);

INSERT INTO storage_provider (id, name, base_url) VALUES 
  (1, 'filegarden', 'https://file.garden');

INSERT INTO bucket (id, name, storage_provider_id) VALUES 
  (1, 'Z-Ko2HO6YkiJFqy0', 1);          

INSERT INTO directory (id, bucket_id, path) VALUES
  (1, 1, 'revar/product');

INSERT INTO image (id, directory_id, filename, alt_text, mime_type) VALUES
  (1, 1, 'XtW7UQUUvtRavdxDsbdvXsXRSfaEUb4x', 'image', 'image/png'),
  (2, 1, 'tTv9vmxLi43jA7rCuaUHhT7wMp9bDnFu', 'image', 'image/webp'),
  (3, 1, 'szddb4jwoUEii2s3o5gYLRZbY3G9crUf', 'image', 'image/webp'),
  (4, 1, 'dFEwi4B4GgXeVwu3PLoRwCUwLJTQMsc3', 'image', 'image/avif'),
  (5, 1, 'ZGdSEUFqs2oZ6goZXwEGduVmwkt6apKy', 'image', 'image/webp'),
  (6, 1, '6ULi4k7DsuDMCaCbWnHNRMNpV2q9VpTJ', 'image', 'image/png'),
  (7, 1, '92onnsiUW5X5xpiRSP4EEGPoQzMi5GmX', 'image', 'image/jpg'),
  (8, 1, 'CcRyKjNmgUjV6W3sYiVzKLjv8zyn8cXt', 'image', 'image/png'),
  (9, 1, 'RtfciKXgPgeB2AwjHe4AYu5VVb5eYGAG', 'image', 'image/jpg'),
  (10, 1, '8Fi4vMTJjktw38PCUQbQapHmhznnfNEA', 'image', 'image/webp');

INSERT INTO product_image (image_id, product_item_id, sort_order) VALUES
  (1, 1, 1),
  (2, 1, 2),
  (3, 2, 3),

  (4, 3, 1),
  (5, 4, 2),

  (6, 5, 1),
  (7, 6, 2),

  (8, 7, 1),

  (9, 8, 1),
  (10, 9, 2);


-- INSERT INTO order_status (code) VALUES 
-- ('PENDING'), ('PAID'), ('SHIPPED'), ('DELIVERED'), ('CANCELLED');